Automated template update to v0.6.0

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -7,24 +7,22 @@ on:
     branches: [main]
   schedule:
     - cron: "0 5 1,15 * *"
-  workflow_dispatch:
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
-# Required for OIDC communication with Codecov
-permissions:
-  id-token: write
-  contents: read
-
 defaults:
   run:
-    # fail on error (-e), on pipes (-o pipefail), and on unset variables (-u)
+    # to fail on error in multiline statements (-e), in pipes (-o pipefail), and on unset variables (-u).
     shell: bash -euo pipefail {0}
 
 jobs:
-  # Get test environments from hatch (defined in pyproject.toml)
+  # Get the test environment from hatch as defined in pyproject.toml.
+  # This ensures that the pyproject.toml is the single point of truth for test definitions and the same tests are
+  # run locally and on continuous integration.
+  # Check [[tool.hatch.envs.hatch-test.matrix]] in pyproject.toml and https://hatch.pypa.io/latest/environment/ for
+  # more details.
   get-environments:
     runs-on: ubuntu-latest
     outputs:
@@ -32,10 +30,10 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
-          # Full fetch depth required for hatch-vcs versioning
+          filter: blob:none
           fetch-depth: 0
       - name: Install uv
-        uses: astral-sh/setup-uv@v6
+        uses: astral-sh/setup-uv@v5
       - name: Get test environments
         id: get-envs
         run: |
@@ -50,48 +48,48 @@ jobs:
               )')
           echo "envs=${ENVS_JSON}" | tee $GITHUB_OUTPUT
 
-  # Run tests through hatch across the defined matrix
+  # Run tests through hatch. Spawns a separate runner for each environment defined in the hatch matrix obtained above.
   test:
     needs: get-environments
-    # Potentially required for Codecov OIDC or env protection rules
-    environment:
-      name: codecov
+
     strategy:
       fail-fast: false
       matrix:
-        # Run on ubuntu only for now
         os: [ubuntu-latest]
         env: ${{ fromJSON(needs.get-environments.outputs.envs) }}
 
-    name: ${{ matrix.env.label }} / ${{ matrix.os }}
+    name: ${{ matrix.env.label }}
     runs-on: ${{ matrix.os }}
 
     steps:
       - uses: actions/checkout@v4
         with:
-          # Full fetch depth required for hatch-vcs versioning
+          filter: blob:none
           fetch-depth: 0
-      - name: Install uv and setup Python
-        uses: astral-sh/setup-uv@v6
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
         with:
           python-version: ${{ matrix.env.python }}
           cache-dependency-glob: pyproject.toml
-      - name: Create hatch environment
+      - name: create hatch environment
         run: uvx hatch env create ${{ matrix.env.name }}
-      - name: Run tests using hatch
+      - name: run tests using hatch
         env:
           MPLBACKEND: agg
-          DISPLAY: :42
           PLATFORM: ${{ matrix.os }}
-        run: uvx hatch run ${{ matrix.env.name }}:run-cov
-      - name: Generate coverage report
-        run: uvx hatch run ${{ matrix.env.name }}:coverage xml
-      - name: Upload coverage to Codecov
+          DISPLAY: :42
+        run: uvx hatch run ${{ matrix.env.name }}:run-cov -v --color=yes -n auto
+      - name: generate coverage report
+        run: |
+          # See https://coverage.readthedocs.io/en/latest/config.html#run-patch
+          test -f .coverage || uvx hatch run ${{ matrix.env.name }}:cov-combine
+          uvx hatch run ${{ matrix.env.name }}:cov-report   # report visibly
+          uvx hatch run ${{ matrix.env.name }}:coverage xml # create report for upload
+      - name: Upload coverage
         uses: codecov/codecov-action@v5
-        with:
-          use_oidc: true
 
-  # Check that all matrix jobs passed
+  # Check that all tests defined above pass. This makes it easy to set a single "required" test in branch
+  # protection instead of having to update it frequently. See https://github.com/re-actors/alls-green#why.
   check:
     name: Tests pass in all hatch environments
     if: always()
@@ -100,7 +98,6 @@ jobs:
       - test
     runs-on: ubuntu-latest
     steps:
-        - name: Check if all jobs succeeded
-          uses: re-actors/alls-green@release/v1
+        - uses: re-actors/alls-green@release/v1
           with:
             jobs: ${{ toJSON(needs) }}
