👷 Update CI to use hatch envs

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -10,56 +10,97 @@ on:
   workflow_dispatch:
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
+  group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+# Required for OIDC communication with Codecov
 permissions:
-  id-token: write # This is required for requesting the JWT
-  contents: read # This is required for actions/checkout
+  id-token: write
+  contents: read
+
+defaults:
+  run:
+    # fail on error (-e), on pipes (-o pipefail), and on unset variables (-u)
+    shell: bash -euo pipefail {0}
 
 jobs:
-  test:
+  # Get test environments from hatch (defined in pyproject.toml)
+  get-environments:
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash -e {0} # -e to fail on error
+    outputs:
+      envs: ${{ steps.get-envs.outputs.envs }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          # Full fetch depth required for hatch-vcs versioning
+          fetch-depth: 0
+      - name: Install uv
+        uses: astral-sh/setup-uv@v6
+      - name: Get test environments
+        id: get-envs
+        run: |
+          ENVS_JSON=$(uvx hatch env show --json | jq -c 'to_entries
+            | map(
+                select(.key | startswith("hatch-test"))
+                | {
+                    name: .key,
+                    label: (if (.key | contains("pre")) then .key + " (PRE-RELEASE DEPENDENCIES)" else .key end),
+                    python: .value.python
+                  }
+              )')
+          echo "envs=${ENVS_JSON}" | tee $GITHUB_OUTPUT
 
+  # Run tests through hatch across the defined matrix
+  test:
+    needs: get-environments
+    # Potentially required for Codecov OIDC or env protection rules
+    environment:
+      name: codecov
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.10", "3.11", "3.12", "3.13"]
+        # Run on ubuntu only for now
+        os: [ubuntu-latest]
+        env: ${{ fromJSON(needs.get-environments.outputs.envs) }}
 
-    name: Python ${{ matrix.python-version }}
-
-    environment:
-      name: codecov
+    name: ${{ matrix.env.label }} / ${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
 
     steps:
-      - name: Checkout ${{ github.ref }}
-        uses: actions/checkout@v4
-
-      - name: Install uv and setup Python
-        uses: astral-sh/setup-uv@v6.0.1
+      - uses: actions/checkout@v4
         with:
-          python-version: ${{ matrix.python-version }}
-          enable-cache: true
-          cache-dependency-glob: "uv.lock"
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Install Dependencies
-        run: |
-          uv sync --extra test --frozen
-
-      - name: Test
+          # Full fetch depth required for hatch-vcs versioning
+          fetch-depth: 0
+      - name: Install uv and setup Python
+        uses: astral-sh/setup-uv@v6
+        with:
+          python-version: ${{ matrix.env.python }}
+          cache-dependency-glob: pyproject.toml
+      - name: Create hatch environment
+        run: uvx hatch env create ${{ matrix.env.name }}
+      - name: Run tests using hatch
         env:
           MPLBACKEND: agg
           DISPLAY: :42
-        run: |
-          uv run --frozen pytest -n auto --cov --cov-report=xml -v --color=yes --junitxml=junit.xml
-
+          PLATFORM: ${{ matrix.os }}
+        run: uvx hatch run ${{ matrix.env.name }}:run-cov
+      - name: Generate coverage report
+        run: uvx hatch run ${{ matrix.env.name }}:coverage xml
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v5
-        env:
-          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
         with:
           use_oidc: true
+
+  # Check that all matrix jobs passed
+  check:
+    name: Tests pass in all hatch environments
+    if: always()
+    needs:
+      - get-environments
+      - test
+    runs-on: ubuntu-latest
+    steps:
+        - name: Check if all jobs succeeded
+          uses: re-actors/alls-green@release/v1
+          with:
+            jobs: ${{ toJSON(needs) }}
